const CONFIG={socials:{telegram:'https://t.me/',vk:'https://vk.com/',whatsapp:'https://wa.me/'},demoMode:true};
const products=[
{id:1,name:'Нежность',category:'Авторские букеты',composition:'Розы, альстромерии, эвкалипт',price:3490,desc:'Воздушная композиция в мягких пастельных оттенках.',image:'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=82'},
{id:2,name:'Облако',category:'Авторские букеты',composition:'Гортензия, розы, сезонная зелень',price:4290,desc:'Объёмный букет с лёгкой садовой атмосферой.',image:'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=900&q=82'},
{id:3,name:'Сад',category:'Авторские букеты',composition:'Сезонные цветы, зелень',price:4990,desc:'Будто только что собранный летний сад.',image:'https://images.unsplash.com/photo-1495231916356-a86217efff12?auto=format&fit=crop&w=900&q=82'},
{id:4,name:'Рассвет',category:'Авторские букеты',composition:'Розы, ранункулюсы, маттиола',price:3790,desc:'Тёплая композиция в оттенках утреннего света.',image:'https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=900&q=82'},
{id:5,name:'Белые розы',category:'Монобукеты',composition:'Белая роза, декоративная зелень',price:3200,desc:'Чистая классика без лишнего.',image:'https://images.unsplash.com/photo-1494972308805-463bc619d34e?auto=format&fit=crop&w=900&q=82'},
{id:6,name:'Пионовидные розы',category:'Монобукеты',composition:'Пионовидная роза',price:4500,desc:'Пышный моно-букет для особенного повода.',image:'https://images.unsplash.com/photo-1455659817273-f96807779a8a?auto=format&fit=crop&w=900&q=82'},
{id:7,name:'Тюльпаны',category:'Монобукеты',composition:'Сезонные тюльпаны',price:2900,desc:'Свежий, лёгкий и очень весенний букет.',image:'https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=900&q=82'},
{id:8,name:'Эустома',category:'Монобукеты',composition:'Эустома, эвкалипт',price:3400,desc:'Нежные фактурные цветы с воздушной зеленью.',image:'https://images.unsplash.com/photo-1507504031003-b417219a0fde?auto=format&fit=crop&w=900&q=82'},
{id:9,name:'Цветочная коробка',category:'Цветы в коробках',composition:'Розы, хризантемы, сезонные цветы',price:4500,desc:'Композиция в лаконичной фирменной коробке.',image:'https://images.unsplash.com/photo-1523691509543-c55fb32e5cee?auto=format&fit=crop&w=900&q=82'},
{id:10,name:'Большая композиция',category:'Цветы в корзинах',composition:'Сезонные цветы, зелень',price:6900,desc:'Пышная композиция для большого события.',image:'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=900&q=82'},
{id:11,name:'Монстера',category:'Комнатные растения',composition:'Монстера, кашпо',price:2500,desc:'Графичное растение для дома или офиса.',image:'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=900&q=82'},
{id:12,name:'Фикус',category:'Комнатные растения',composition:'Фикус, кашпо',price:2900,desc:'Зелёный акцент, который легко вписывается в интерьер.',image:'https://images.unsplash.com/photo-1604762524889-3e2fcc145683?auto=format&fit=crop&w=900&q=82'}];
let cart=JSON.parse(localStorage.getItem('zelen-cart')||'[]');let activeCategory='Все';let selectedProduct=null;let selectedPrice=0;
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function save(){localStorage.setItem('zelen-cart',JSON.stringify(cart));renderCart();document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function renderFilters(){const cats=['Все','Авторские букеты','Монобукеты','Цветы в коробках','Цветы в корзинах','Комнатные растения'];document.getElementById('filters').innerHTML=cats.map(c=>`<button class="filter ${c===activeCategory?'active':''}" data-cat="${c}">${c}</button>`).join('');document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderFilters();renderProducts()})}
function renderProducts(){let list=activeCategory==='Все'?products:products.filter(p=>p.category===activeCategory);document.getElementById('products').innerHTML=list.map(p=>`<article class="product"><div class="product-image" data-view="${p.id}"><img src="${p.image}" alt="${p.name}" loading="lazy"></div><div class="product-info"><h3>${p.name}</h3><p>${p.composition}</p><strong class="product-price">${money(p.price)}</strong><div class="product-actions"><button data-view="${p.id}">Подробнее</button><button class="add" data-add="${p.id}">В корзину</button></div></div></article>`).join('');document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(+b.dataset.add));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>openProduct(+b.dataset.view))}
function add(id,qty=1){const p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id);if(item)item.qty+=qty;else cart.push({id,qty});save();openCart()}
function renderCart(){const box=document.getElementById('cartItems');if(!cart.length){box.innerHTML='<div style="padding:70px 0;text-align:center;color:#777">В вашей корзине пока пусто.<br><br>Самое время выбрать что-нибудь красивое 🌿</div>';document.getElementById('cartTotal').textContent='0 ₽';return}box.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);return `<div class="cart-row"><img src="${p.image}" alt="${p.name}"><div><h4>${p.name}</h4><p>${money(p.price)}</p><div class="qty"><button data-dec="${p.id}">−</button><span>${i.qty}</span><button data-inc="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">Удалить</button></div>`}).join('');let total=cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0);document.getElementById('cartTotal').textContent=money(total);document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>add(+b.dataset.inc));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>{const i=cart.find(x=>x.id===+b.dataset.dec);i.qty--;if(i.qty<1)cart=cart.filter(x=>x.id!==i.id);save()});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);save()})}
function openCart(){document.getElementById('cartDrawer').classList.add('open');document.getElementById('overlay').classList.add('show')};function closeCart(){document.getElementById('cartDrawer').classList.remove('open');document.getElementById('overlay').classList.remove('show')}
function openProduct(id){selectedProduct=products.find(p=>p.id===id);selectedPrice=selectedProduct.price;document.getElementById('modalImage').src=selectedProduct.image;document.getElementById('modalTitle').textContent=selectedProduct.name;document.getElementById('modalCategory').textContent=selectedProduct.category;document.getElementById('modalDesc').textContent=selectedProduct.desc;document.getElementById('modalComposition').textContent='Состав: '+selectedProduct.composition;document.getElementById('modalPrice').textContent=money(selectedPrice);document.getElementById('modalSizes').innerHTML='<button class="size active">Стандарт</button><button class="size">Большой +1 500 ₽</button>';document.querySelectorAll('.size').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('.size').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedPrice=selectedProduct.price+(i?1500:0);document.getElementById('modalPrice').textContent=money(selectedPrice)});document.getElementById('productModal').classList.add('show')}
function closeModal(id){document.getElementById(id).classList.remove('show')}
function checkout(){if(!cart.length)return;closeCart();let total=cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0);document.getElementById('checkoutSummary').innerHTML=cart.map(i=>{let p=products.find(x=>x.id===i.id);return `<div class="summary-line"><span>${p.name} × ${i.qty}</span><b>${money(p.price*i.qty)}</b></div>`}).join('')+`<hr><div class="summary-line"><strong>Итого</strong><strong>${money(total)}</strong></div>`;document.getElementById('checkoutModal').classList.add('show')}
function orderNumber(){let n=Number(localStorage.getItem('zelen-order')||1000)+1;localStorage.setItem('zelen-order',n);return n}
function submitOrder(e){e.preventDefault();const data=new FormData(e.target),num=orderNumber();const order={number:num,items:cart.map(i=>{let p=products.find(x=>x.id===i.id);return {name:p.name,qty:i.qty,price:p.price}}),...Object.fromEntries(data.entries()),total:cart.reduce((s,i)=>s+products.find(p=>p.id===i.id).price*i.qty,0),createdAt:new Date().toISOString()};localStorage.setItem('zelen-last-order',JSON.stringify(order));console.log('DEMO ORDER — send this payload from backend to Telegram:',order);cart=[];save();closeModal('checkoutModal');document.getElementById('orderNumber').textContent=num;document.getElementById('success').classList.add('show')}
function setSocials(){document.querySelectorAll('[data-social]').forEach(a=>{let key=a.dataset.social;a.href=CONFIG.socials[key]||'#';a.target='_blank';a.rel='noopener'})}
document.getElementById('openCart').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;document.getElementById('overlay').onclick=closeCart;document.getElementById('checkoutBtn').onclick=checkout;document.getElementById('modalAdd').onclick=()=>{add(selectedProduct.id);closeModal('productModal')};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.getElementById('checkoutForm').onsubmit=submitOrder;document.getElementById('closeSuccess').onclick=()=>closeModal('success');document.getElementById('menuBtn').onclick=()=>document.querySelector('.header nav').classList.toggle('mobile-open');document.querySelectorAll('.header nav a').forEach(a=>a.onclick=()=>document.querySelector('.header nav').classList.remove('mobile-open'));renderFilters();renderProducts();renderCart();setSocials();
